# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df47be38472cd80673806caaff725d62a7bbfe61b140408dcbfdedf52ce6e248355dfb1699e5202658f289612ba01f74059e8b34c3cd23447d5ed820490b9487

test:
  secret_key_base: 4ed846012f9e901e47d95c3147b03af64339a930419cdb58420f0696238a49439cbc7d0594bb6a6c779d9cb23ef6d1b5a6a7286e12c5404b668f91d2a3ea4182

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
